// <auto-generated />
using AutoInspectors.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutoInspectors.Migrations
{
    [DbContext(typeof(AutoInspectorsContext))]
    [Migration("20171009215411_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoInspectors.Models.Inspection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AirFilter");

                    b.Property<string>("AlternatorTest");

                    b.Property<string>("BatteryTest");

                    b.Property<string>("BrakeFluid");

                    b.Property<string>("CoolantLevel");

                    b.Property<string>("CoolantPH");

                    b.Property<string>("DTCCode");

                    b.Property<string>("EngineOil");

                    b.Property<string>("FrontBrakes");

                    b.Property<string>("Hoses");

                    b.Property<string>("RearBrakes");

                    b.Property<string>("TireRotation");

                    b.Property<string>("Transmission");

                    b.Property<string>("Wires");

                    b.HasKey("ID");

                    b.ToTable("Inspection");
                });

            modelBuilder.Entity("AutoInspectors.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("EngineSize");

                    b.Property<string>("LicensePlate")
                        .IsRequired();

                    b.Property<string>("Make")
                        .IsRequired();

                    b.Property<int>("Mileage");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("TransmissionType")
                        .IsRequired();

                    b.Property<string>("VIN")
                        .IsRequired();

                    b.Property<int>("Year");

                    b.HasKey("ID");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
