// <auto-generated />
using AutoInspectors.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutoInspectors.Migrations
{
    [DbContext(typeof(AutoInspectorsContext))]
    [Migration("20171010185409_TableConnections")]
    partial class TableConnections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoInspectors.Models.Inspection", b =>
                {
                    b.Property<int>("InspectionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AirFilter");

                    b.Property<string>("AlternatorTest");

                    b.Property<string>("BatteryTest");

                    b.Property<string>("BrakeFluid");

                    b.Property<string>("CoolantLevel");

                    b.Property<string>("CoolantPH");

                    b.Property<string>("DTCCode");

                    b.Property<string>("EngineOil");

                    b.Property<string>("FrontBrakes");

                    b.Property<string>("Hoses");

                    b.Property<string>("RearBrakes");

                    b.Property<string>("TireRotation");

                    b.Property<string>("TransmissionFluid");

                    b.Property<int>("VehicleID");

                    b.Property<string>("Wires");

                    b.HasKey("InspectionID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Inspection");
                });

            modelBuilder.Entity("AutoInspectors.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EngineSize")
                        .IsRequired();

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Make")
                        .IsRequired();

                    b.Property<int>("Mileage");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("TransmissionType")
                        .IsRequired();

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17);

                    b.Property<int>("Year");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("AutoInspectors.Models.Inspection", b =>
                {
                    b.HasOne("AutoInspectors.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
